# Which of these categories have a rail connection on the fantasy map?

airports = {
    "(ATL) Atlanta": 1,
    "(BOS) Boston": 1,
    "(BUR) Hollywood-Burbank": 1,
    "(BWI) Baltimore": 1,
    "(CLE) Cleveland": 1,
    "(CLT) Charlotte": 1,
    "(CMH) Columbus": 1,
    "(CVG) Cincinnati": 1,
    "(DCA) Washington National": 1,
    "(DEN) Denver": 1,
    "(DFW) Dallas-Fort Worth": 1,
    "(DTW) Detroit": 1,
    "(EWR) Newark Liberty": 1,
    "(HOU) Houston Hobby": 1,
    "(IAD) Washington Dulles": 1,
    "(IAH) Houston Intercontinental": 1,
    "(IND) Indianapolis": 1,
    "(PDX) Portland": 1,
    "(PGH) Pittsburgh": 1,
    "(DEN) Denver": 1,
    "(JFK) New York-JFK": 1,
    "(LAS) Las Vegas": 1,
    "(LAX) Los Angeles": 1,
    "(LGA) New York-La Guardia": 1,
    "(MCI) Kansas City": 1,
    "(MCO) Orlando": 1,
    "(MDW) Chicago Midway": 1,
    "(MIA) Miami": 1,
    "(MKE) Milwaukee": 1,
    "(OAK) Oakland": 1,
    "(OKC) Oklahoma City": 1,
    "(ORD) Chicago O'Hare": 1,
    "(PHL) Philadelphia": 1,
    "(PHX) Phoenix": 1,
    "(SBD) South Bend": 1,
    "(SEA) Seattle-Tacoma": 1,
    "(SFO) San Francisco": 1,
    "(STL) St. Louis": 1,
    "(YEG) Edmonton": 1,
    "(YOW) Ottawa": 1,
    "(YUL) Montréal": 1,
    "(YVR) Vancouver": 1,
    "(YYC) Calgary": 1,
    "(YYZ) Toronto": 1,

    "(AUS) Austin-Bergstrom": 0,
    "(BNA) Nashville": 0,
    "(BUF) Buffalo Nuagara": 0,
    "(JAX) Jacksonville": 0,
    "(MCC) Sacramento": 0,
    "(MEM) Memphis": 0,
    "(MSY) New Orleans": 0,
    "(RDU) Raleigh-Durham": 0,
    "(SAT) San Antonio": 0,
    "(SDF) Louisville": 0,
    "(SJC) San Jose": 0,
    "(TPA) Tampa": 0,
    "(YWG) Winnipeg": 0,
}

universities = {
    "Arizona State University": 1,
    "Auburn University": 1,
    "Baylor University": 1,
    "Brown University": 1,
    "Carnegie Mellon University": 1,
    "Case Western Reserve University": 1,
    "City University of New York": 1,
    "Clemson University": 1,
    "Colorado Mesa University": 1,
    "Colorado State University": 1,
    "Columbia University": 1,
    "Concordia University": 1,
    "Coppin State University": 1,
    "Duke University": 1,
    "Eastern Michigan University": 1,
    "Emory University": 1,
    "Georgia State University": 1,
    "George Washington University": 1,
    "Georgia Institute of Technology": 1,
    "Harvard University": 1,
    "Loyola University Chicago": 1,
    "Massachussetts Institute of Technology": 1,
    "McGill University": 1,
    "Metropolitan State University of Denver": 1,
    "Michigan State University": 1,
    "Montana State University": 1,
    "Montclair State University": 1,
    "North Carolina University": 1,
    "North Dakota State University": 1,
    "Northern Arizona University": 1,
    "Northwestern University": 1,
    "Ohio University": 1,
    "Oklahoma State University-Tulsa": 1,
    "Pennsylvania State University": 1,
    "Polytechnique Montréal": 1,
    "Portland State University": 1,
    "Princeton University": 1,
    "Purdue University": 1,
    "Rice University": 1,
    "Rowan University": 1,
    "Rutgers University": 1,
    "San Diego State University": 1,
    "Santa Clara University": 1,
    "South Dakota School of Mines": 0,
    "Stanford University": 1,
    "Texas A&M University": 1,
    "Texas Southern University": 1,
    "The Master's University": 1,
    "The Ohio State University": 1,
    "The University of Alabama": 1,
    "The University of Chicago": 1,
    "The University of Texas at Austin": 1,
    "The University of Utah": 1,
    "Thomas Jefferson University": 1,
    "Université de Montréal": 1,
    "Université du Québec à Montréal": 1,
    "Université du Québec à Trois-Rivieres": 1,
    "University at Buffalo": 1,
    "University of Alberta": 1,
    "University of Arizona-Phoenix": 1,
    "University of Arizona-Tucson": 1,
    "University of British Columbia-Vancouver": 1,
    "University of Calgary": 1,
    "University of California-Berkeley": 1,
    "University of California-Davis": 1,
    "University of California-Los Angeles": 1,
    "University of California-San Diego": 1,
    "University of California-San Francisco": 1,
    "University of Cincinnati": 1,
    "University of Colorado-Boulder": 1,
    "University of Colorado-Denver": 1,
    "University of Dallas": 1,
    "University of Dayton": 1,
    "University of Denver": 1,
    "University of Guelph": 1,
    "University of Houston": 1,
    "University of Illinois at Urbana-Champaign": 1,
    "University of Illinois-Chicago": 1,
    "University of Indianapolis": 1,
    "University of Maryland-College Park": 1,
    "University of Memphis": 1,
    "University of Miami": 1,
    "University of Michigan-Ann Arbor": 1,
    "University of Michigan-Dearborn": 1,
    "University of Minnesota-Crookston": 1,
    "University of Minnesota-Twin Cities": 1,
    "University of Missouri-Kansas City": 1,
    "University of Montana": 1,
    "University of Nevada-Las Vegas": 1,
    "University of North Carolina at Charlotte": 0,
    "University of North Dakota": 1,
    "University of North Texas-Dallas": 1,
    "University of Oklahoma": 1,
    "University of Oregon": 1,
    "University of Ottawa": 1,
    "University of Pennsylvania": 1,
    "University of Redlands": 1,
    "University of San Francisco": 1,
    "University of South Carolina": 1,
    "University of Southern California": 1,
    "University of Toronto-St. George": 1,
    "University of Virginia": 1,
    "University of Washington-Seattle": 1,
    "University of Waterloo": 1,
    "University of Wyoming": 1,
    "Valparaiso University": 1,
    "Washington University in St. Louis": 1,
    "West Virginia University-Morgantown": 1,
    "West Virginia University-Parkersburg": 1,
    "Western Michigan University": 1,

    "Brigham Young University": 0,
    "British Columbia Institute of Technology": 0,
    "California Institute of Technology": 0,
    "Colorado School of Mines": 0,
    "Cornell University": 0,
    "Florida International University": 0,
    "Grand Canyon University": 0,
    "Iowa State University": 0,
    "South Carolina State University": 0,
    "Texas Christian University": 0,
    "The University of New Orleans": 0,
    "The University of Tampa": 0,
    "Université Laval": 0,
    "University of Arkansas at Little Rock": 0,
    "University of California-Irvine": 0,
    "University of California-Riverside": 0,
    "University of California-Santa Barbara": 0,
    "University of Central Florida": 0,
    "University at Colorado-Colorado Springs": 0,
    "University of Florida": 0,
    "University of Georgia": 0,
    "University of Kansas": 0,
    "University of Louisville": 0,
    "University of Manitoba": 0,
    "University of Nebraska-Lincoln": 0,
    "University of Nebraska-Omaha": 0,
    "University of Nevada-Reno": 0,
    "University of New Mexico": 0,
    "University of North Carolina-Chapel Hill": 0,
    "University of Notre Dame": 0,
    "University of Phoenix": 0,
    "University of South Florida-St. Petersburg": 0,
    "University of South Florida-Tampa": 0,
    "University of Toronto-Mississauga": 0,
    "University of Toronto-Scarborough": 0,
    "Vanderbilt University": 0,
    "Virginia Commonwealth University": 0,
    "Wichita State University": 0,
}